### ISSUE TITLE
After the node completely withdrew staking, the withdrew delegate causes the node to panic

### ISSUE THREAD

**Issue by awake006** [PlatONnetwork/PlatON-Go#1084]
Hi there,

After the node completely withdrew staking, the withdrew delegate causes the node to panic

#### System information

PlatON version: `0.7.6`
OS & Version: Windows/Linux/OSX
Commit hash : c5885ecdaf08a4df47ab9160f61592f5f2575997

1. The first settlement cycle, staking a node and delegate
2. The second settlement cycle, withdrew staking and wait for 3 settlement cycles
3. Fifth settlement cycle, withdrew delegate
Expected result: Redemption succeeded
Actual result: node panic

#### Backtrace

````
TRACE[01-09|08:08:17.034|miner/worker.go:1089]                      Validator mode                           mode=ppos
TRACE[01-09|08:08:17.034|core/tx_pool.go:724]                       Get pending                              duration=14.43µs
DEBUG[01-09|08:08:17.034|miner/worker.go:1120]                      Fetch pending transactions success       pendingLength=1 time=26.443µs
DEBUG[01-09|08:08:17.034|miner/worker.go:1158]                      Execute pending transactions             number=806           localTxCount=0 remoteTxCount=1 txsCount=1
DEBUG[01-09|08:08:17.034|miner/worker.go:1172]                      Local transactions executing stat        number=806           involvedTxCount=0 time=156ns
DEBUG[01-09|08:08:17.034|core/types/transaction.go:326]             NewTransactionsByPriceAndNonce           txsCount=1
DEBUG[01-09|08:08:17.034|core/vm/staking_contract.go:703]           Call withdrewDelegate of stakingContract txHash=0x9039f4bb7a506ba6bdb7e3d8040d14d2b68080b905994acaa356b4e6d971e2e9 blockNumber=806 delAddr=0xe3944a50BD550a16058D346dbBc7E19891F94d5F nodeId=c7fd41525269f14af9b737668fe9022207f85fcbe4b5149d7e5a4302230b65f0d83c5439c64a4ac4d9a6ed29b1a90727ab28d675a870af2349f93bc632a0ca4d stakingNum=15 amount=10000000000000000000
DEBUG[01-09|08:08:17.034|x/plugin/staking_plugin.go:2482]           lazyCalcDelegateAmount before            epoch=6  del="{\"DelegateEpoch\": \"1\",\"Released\": \"0\",\"ReleasedHes\": 100000000000000000000,\"RestrictingPlan\": 0,\"RestrictingPlanHes\": 0,\"CumulativeIncome\": 0}"
DEBUG[01-09|08:08:17.034|x/plugin/staking_plugin.go:2499]           lazyCalcDelegateAmount end               epoch=6  del="{\"DelegateEpoch\": \"1\",\"Released\": \"100000000000000000000\",\"ReleasedHes\": 0,\"RestrictingPlan\": 0,\"RestrictingPlanHes\": 0,\"CumulativeIncome\": 0}"
DEBUG[01-09|08:08:17.034|x/plugin/staking_plugin.go:2482]           lazyCalcDelegateAmount before            epoch=6  del="{\"DelegateEpoch\": \"1\",\"Released\": \"100000000000000000000\",\"ReleasedHes\": 0,\"RestrictingPlan\": 0,\"RestrictingPlanHes\": 0,\"CumulativeIncome\": 271680748729900000000000}"
DEBUG[01-09|08:08:17.034|x/plugin/staking_plugin.go:2499]           lazyCalcDelegateAmount end               epoch=6  del="{\"DelegateEpoch\": \"1\",\"Released\": \"100000000000000000000\",\"ReleasedHes\": 0,\"RestrictingPlan\": 0,\"RestrictingPlanHes\": 0,\"CumulativeIncome\": 271680748729900000000000}"
DEBUG[01-09|08:08:17.034|x/plugin/staking_plugin.go:2537]           Call calcDelegateIncome end              currEpoch=6 perLen=1 delegateRewardReceivesLen=1 totalDelegate=100000000000000000000 totalHes=0 income=271680748729900000000000
DEBUG[01-09|08:08:17.034|consensus/cbft/sync_process.go:778]        Get avg latency                          epoch=21 view=0                       avg=0
DEBUG[01-09|08:08:17.034|consensus/cbft/cbft.go:1155]               Calc next block time                     epoch=21 view=0                       blockTime=2020-01-09T08:08:17+0000  now=2020-01-09T08:08:17+0000 produceInterval=1s period=10000 amount=10                          interval=2.901024ms   rtt=200ms executeTime=400ms
DEBUG[01-09|08:08:17.034|miner/worker.go:1016]                      Next block time                          time="2020-01-09 08:08:17.632"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb26bb1]

goroutine 104 [running]:
github.com/PlatONnetwork/PlatON-Go/x/plugin.(*StakingPlugin).WithdrewDelegate(0xc00024d3a0, 0x15b2b80, 0xc02f0a06c0, 0x0, 0x0, 0x0, 0x0, 0xc02f38ed60, 0xc02f38f0e0, 0x160a55bd504a94e3, ...)
        /home/platon/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/x/plugin/staking_plugin.go:913 +0xa31
github.com/PlatONnetwork/PlatON-Go/core/vm.(*StakingContract).withdrewDelegate(0xc02f38ef40, 0xf, 0x4af169525241fdc7, 0x2202e98f6637b7f9, 0x9d14b5e4cb5ff807, 0xf0650b2302435a7e, 0xc44a4ac639543cd8, 0x2707a9b129eda6d9, 0x23af70a875d628ab, 0x4dcaa032c63bf949, ...)
        /home/platon/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/core/vm/staking_contract.go:754 +0x9ae
reflect.Value.call(0x1197a00, 0xc030a10230, 0x13, 0x130f1a4, 0x4, 0xc0309964b0, 0x3, 0x3, 0x15430d6, 0xc009a0d5e0, ...)
        /opt/go1.11.3/src/reflect/value.go:460 +0x5f6
reflect.Value.Call(0x1197a00, 0xc030a10230, 0x13, 0xc0309964b0, 0x3, 0x3, 0xc030a10230, 0xc0309964b0, 0x3)
        /opt/go1.11.3/src/reflect/value.go:321 +0xb4
github.com/PlatONnetwork/PlatON-Go/core/vm.execPlatonContract(0xc0099e60c0, 0x55, 0x55, 0xc03d171620, 0xc02f38ef40, 0xc009c3f318, 0x43de82, 0xc002d82000, 0x7f45a90afd98)
        /home/platon/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/core/vm/platon_contract_tool.go:39 +0x234
github.com/PlatONnetwork/PlatON-Go/core/vm.(*StakingContract).Run(0xc02f38ef40, 0xc0099e60c0, 0x55, 0x55, 0x1770, 0x20, 0x1218b40, 0x108d901, 0xc02f38ef40)
        /home/platon/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/core/vm/staking_contract.go:80 +0x5b
github.com/PlatONnetwork/PlatON-Go/core/vm.RunPlatONPrecompiledContract(0x15990c0, 0xc02f38ef40, 0xc0099e60c0, 0x55, 0x55, 0xc02f0a0b40, 0xc03d1715f0, 0xc009c3f3c8, 0x44995d, 0x12b7680, ...)
        /home/platon/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/core/vm/contracts.go:111 +0xe3
github.com/PlatONnetwork/PlatON-Go/core/vm.run(0xc0001a4a80, 0xc02f0a0b40, 0xc0099e60c0, 0x55, 0x55, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/platon/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/core/vm/evm.go:71 +0x599
github.com/PlatONnetwork/PlatON-Go/core/vm.(*EVM).Call(0xc0001a4a80, 0x1576820, 0xc03d0ff0e0, 0x10, 0x0, 0x2000000, 0xc0099e60c0, 0x55, 0x55, 0x36b0, ...)
        /home/platon/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/core/vm/evm.go:272 +0x535
github.com/PlatONnetwork/PlatON-Go/core.(*StateTransition).TransitionDb(0xc000169340, 0x15a4600, 0xc035772240, 0xc02e31eb28, 0xc000169340, 0xc035772240, 0xc035772240, 0x12cbaa0)
        /home/platon/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/core/state_transition.go:218 +0x366
github.com/PlatONnetwork/PlatON-Go/core.ApplyMessage(0xc0001a4a80, 0x15a4600, 0xc035772240, 0xc02e31eb28, 0x98e1c7bb6d348d05, 0x5f4df991, 0xc02f38eda0, 0x10, 0x0, 0x3000000, ...)
        /home/platon/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/core/state_transition.go:130 +0x5b
github.com/PlatONnetwork/PlatON-Go/core.ApplyTransaction(0xc00027a280, 0x1588780, 0xc00261a000, 0xc02e31eb28, 0xc02f0a06c0, 0xc02ea45440, 0xc02f726bd0, 0xc02ea455e8, 0x0, 0x0, ...)
        /home/platon/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/core/state_processor.go:115 +0x2cb
````

**Comment by awake006** [comment]
Verification succeeded in d0c2cf534cdcd193f208b9b7417bb35ea099f086
