### ISSUE TITLE
contract migrate fail

### ISSUE THREAD

**Issue by fksyuan** [PlatONnetwork/PlatON-Go#1161]
when contract constructor have parameter，the migrate will fail。

the java sdk throw the following error：
ContractDistoryTest failure,exception msg:
Transaction has failed with status: 0x0. Gas used: 90000000. (not-enough gas?)
org.web3j.protocol.exceptions.TransactionException: Transaction has failed with status: 0x0. Gas used: 90000000. (not-enough gas?)
	at org.web3j.tx.WasmContract.executeTransaction(WasmContract.java:160)
	at org.web3j.tx.WasmContract.executeTransaction(WasmContract.java:152)
	at org.web3j.tx.WasmContract.executeTransaction(WasmContract.java:147)
	at org.web3j.tx.WasmContract.lambda$executeRemoteCallTransaction$1(WasmContract.java:168)
	at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:30)
	at wasm.contract_migrate.ContractMigrateVariableTest.testMigrateContractBalance(ContractMigrateVariableTest.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at network.platon.autotest.junit.rules.DriverService$1.evaluate(DriverService.java:134)
	at org.junit.rules.Verifier$1.evaluate(Verifier.java:35)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
测试用例（用例一）执行结束。	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)

**Comment by fksyuan** [comment]
the contract is：

#include <platon/platon.hpp>
using namespace platon;

CONTRACT ContractMigrateOld: public platon::Contract {
	public:
		PLATON_EVENT1(transfer,std::string,std::string)
		ACTION void init(uint8_t input) {
		  tUint8.self() = input;
    }

		ACTION std::string migrate_contract(const bytes &init_arg, uint64_t transfer_value, uint64_t gas_value) {
        DEBUG("init_arg is :", toHex(init_arg));
        Address return_address;
        platon_migrate_contract(return_address, init_arg, transfer_value, gas_value);
        PLATON_EMIT_EVENT1(transfer,return_address.toString(),return_address.toString());
        DEBUG("new contract address:", return_address.toString());
        return return_address.toString();
    }

		ACTION void setUint8(uint8_t input)
		{
			tUint8.self() = input;
		}
		CONST uint8_t getUint8()
		{
			return tUint8.self();
		}

	private:
	  platon::StorageType<"suint8"_n, uint8_t> tUint8;
};

PLATON_DISPATCH(ContractMigrateOld,(init)(setUint8)(getUint8))

**Comment by GavinXu520** [comment]
![image](https://user-images.githubusercontent.com/13655605/74537827-cdc18080-4f75-11ea-9dd3-2e7a6d82a88d.png)
Because the function  `migrate_contract` is not declared in PLATON_DISPATCH.
