### ISSUE TITLE
Conversion of address type returned by `platon_origin ()` failed.

### ISSUE THREAD

**Issue by zjsunzone** [PlatONnetwork/PlatON-Go#1200]
Hi there,

Conversion of address type returned by `platon_origin ()` failed.

#### System information

PlatON version: `platon version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Steps to reproduce the behaviour

Contract Code:

```
...
/// define: Address platon_origin();
CONST Address origin() {
	Address ori = platon::platon_origin();
	return ori;		
}
...
```

#### Backtrace

````
Value -4c80ba6060f9cd3a80edb82b6a5e2695c2a4c3ebis larger then length 40
java.lang.UnsupportedOperationException: Value -4c80ba6060f9cd3a80edb82b6a5e2695c2a4c3ebis larger then length 40
	at org.web3j.utils.Numeric.toHexStringZeroPadded(Numeric.java:134)
	at org.web3j.utils.Numeric.toHexStringWithPrefixZeroPadded(Numeric.java:114)
	at com.platon.rlp.datatypes.WasmAddress.<init>(WasmAddress.java:23)
	at com.platon.rlp.RLPCodec.decode(RLPCodec.java:80)
	at com.platon.rlp.RLPCodec.decode(RLPCodec.java:34)
	at org.web3j.abi.WasmReturnDecoder.decode(WasmReturnDecoder.java:12)
	at org.web3j.tx.WasmContract.executeCall(WasmContract.java:145)
	at org.web3j.tx.WasmContract.lambda$executeRemoteCall$0(WasmContract.java:150)
	at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:30)
	at wasm.contract_func.ContractInnerFunctionTest.testFunctionContract_02(ContractInnerFunctionTest.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at network.platon.autotest.junit.rules.DriverService$1.evaluate(DriverService.java:134)
	at org.junit.rules.Verifier$1.evaluate(Verifier.java:35)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
````

**Comment by lhdeng** [comment]
The hexadecimal conversion failed because the address type turned into a BigInteger and became a negative number.This issue has been resolved in the latest release.
