### ISSUE TITLE
Restart node panic

### ISSUE THREAD

**Issue by awake006** [PlatONnetwork/PlatON-Go#1244]
Hi there,

When I restart after modifying "NetworkId", the node appears panic

#### System information

PlatON version: `0.10.2`
OS & Version: Windows/Linux/OSX
Commit hash : e5ea70a9db7efe962a7cd310efa7affe1a71bc5d

#### Expected behaviour

restart success
#### Actual behaviour
panic

#### Steps to reproduce the behaviour

1.init 
2.start node
3.stop node
4.update NetworkId
5.start node
#### Backtrace

````
INFO [03-11|14:22:57.412|core/snapshotdb/snapshotdb.go:238]      begin recover                            package=snapshotdb path=/home/platon/trantor_test/node-16789/data/platon/snapshotdb
INFO [03-11|14:22:57.412|core/snapshotdb/snapshotdb.go:242]      load current                             package=snapshotdb base=&{Num:+230} high="&{Num:+240 Hash:[241 211 30 150 189 59 248 142 69 186 5 0 199 143 226 255 166 114 18 76 169 89 18 25 113 30 59 94 235 239 211 137]}"
ERROR[03-11|14:22:57.412|core/snapshotdb/snapshotdb.go:244]      recover db fail:                         package=snapshotdb error="current baseNum and highestNum is not same,but not wal find"
ERROR[03-11|14:22:57.412|core/snapshotdb/snapshotdb.go:192]      init db fail                             package=snapshotdb err="current baseNum and highestNum is not same,but not wal find"
panic: current baseNum and highestNum is not same,but not wal find

goroutine 1 [running]:
github.com/PlatONnetwork/PlatON-Go/core/snapshotdb.Instance(0x0, 0x0)
	/home/platon/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/core/snapshotdb/snapshotdb.go:193 +0x33f
github.com/PlatONnetwork/PlatON-Go/x/gov.get(0x84c1dc5b4e8bc5db, 0x68a85898147c50ab, 0x27b9c772b0c31e9, 0x17b806a004157381, 0xc0000381e0, 0x21, 0x21, 0x21, 0x21, 0x60, ...)
	/home/platon/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/x/gov/gov_snapdb.go:29 +0x26
github.com/PlatONnetwork/PlatON-Go/x/gov.findGovernParamValue(0x13caf21, 0x5, 0x13dd7a9, 0x10, 0x84c1dc5b4e8bc5db, 0x68a85898147c50ab, 0x27b9c772b0c31e9, 0x17b806a004157381, 0xc000000008, 0x1432958, ...)
	/home/platon/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/x/gov/gov_snapdb.go:255 +0x1a0
github.com/PlatONnetwork/PlatON-Go/x/gov.GetGovernParamValue(0x13caf21, 0x5, 0x13dd7a9, 0x10, 0x0, 0x84c1dc5b4e8bc5db, 0x68a85898147c50ab, 0x27b9c772b0c31e9, 0x17b806a004157381, 0x27b9c772b0c31e9, ...)
	/home/platon/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/x/gov/gov.go:644 +0x84
github.com/PlatONnetwork/PlatON-Go/x/gov.GovernMaxBlockGasLimit(0x0, 0x84c1dc5b4e8bc5db, 0x68a85898147c50ab, 0x27b9c772b0c31e9, 0x17b806a004157381, 0x41, 0x34630b8a000, 0x1)
	/home/platon/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/x/gov/gov.go:774 +0x73
github.com/PlatONnetwork/PlatON-Go/eth.New(0xc000198000, 0xc0004b4000, 0x30, 0x136b600, 0xc0004a97c8)
	/home/platon/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/eth/backend.go:237 +0xb8f
github.com/PlatONnetwork/PlatON-Go/cmd/utils.RegisterEthService.func2(0xc000198000, 0xc00019c3f0, 0xc0004a9980, 0xc0001a62c0, 0x2)
	/home/platon/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/cmd/utils/flags.go:1281 +0x46
github.com/PlatONnetwork/PlatON-Go/node.(*Node).Start(0xc000452000, 0x0, 0x0)
	/home/platon/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/node/node.go:197 +0x414
github.com/PlatONnetwork/PlatON-Go/cmd/utils.StartNode(0xc000452000)
	/home/platon/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/cmd/utils/cmd.go:67 +0x2f
main.startNode(0xc0000e5b80, 0xc000452000)
	/home/platon/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/cmd/platon/main.go:304 +0x7e
main.geth(0xc0000e5b80, 0xc0000e5b80, 0xc0004a9b9f)
	/home/platon/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/cmd/platon/main.go:292 +0xe3
github.com/PlatONnetwork/PlatON-Go/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0x11f5cc0, 0x1434fc8, 0xc0000e5b80, 0xc000310cc0, 0x0)
	/home/platon/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/vendor/gopkg.in/urfave/cli.v1/app.go:490 +0xc8
github.com/PlatONnetwork/PlatON-Go/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc00030e340, 0xc0000321c0, 0x1b, 0x1c, 0x0, 0x0)
	/home/platon/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/vendor/gopkg.in/urfave/cli.v1/app.go:264 +0x58c
main.main()
	/home/platon/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/cmd/platon/main.go:278 +0x55

````

**Comment by awake006** [comment]
Restart without modifying "NetworkId", panic also appears（不修改NetworkId也会出现该问题）

**Comment by cheng762** [comment]
Lack of environment, can not confirm what the problem is, there are two doubts from the log. 1. The block height of the current chain has been confirmed to 330, but when restarting, the block height obtained by calling blockchain.CurrentHeader () is 240 2. When restarting, the snapshot DB is missing the wal log between 230-330, causing an error current baseNum and highestNum is not same, but not wal find, but from the log, 230-330 logs are written successfully

**Comment by awake006** [comment]
Cannot reproduce too long
