### ISSUE TITLE
platon-cpp generated java packaging class error.

### ISSUE THREAD

**Issue by qcxiao** [PlatONnetwork/PlatON-Go#1385]
Hi there,

abi errors generated after compilation,
platon-cpp generated java packaging class error.

#### System information

PlatON version: `0.13.0`

#### Expected behaviour
a successful java wrapper class

#### Actual behaviour
`
Generating network.platon.contracts.Eventer ... Exception in thread "main" java.lang.IllegalArgumentException: not a valid name: 
	at com.squareup.javapoet.Util.checkArgument(Util.java:64)
	at com.squareup.javapoet.FieldSpec.builder(FieldSpec.java:92)
	at com.squareup.javapoet.TypeSpec$Builder.addField(TypeSpec.java:499)
	at org.web3j.codegen.SolidityFunctionWrapper.buildEventResponseObject(SolidityFunctionWrapper.java:738)
	at org.web3j.codegen.SolidityFunctionWrapper.buildEventFunctions(SolidityFunctionWrapper.java:881)
	at org.web3j.codegen.SolidityFunctionWrapper.buildFunctionDefinitions(SolidityFunctionWrapper.java:257)
	at org.web3j.codegen.SolidityFunctionWrapper.generateJavaFiles(SolidityFunctionWrapper.java:132)
	at org.web3j.codegen.SolidityFunctionWrapper.generateJavaFiles(SolidityFunctionWrapper.java:114)
	at org.web3j.codegen.SolidityFunctionWrapperGenerator.generate(SolidityFunctionWrapperGenerator.java:107)
	at org.web3j.codegen.SolidityFunctionWrapperGenerator.main(SolidityFunctionWrapperGenerator.java:72)
	at org.web3j.codegen.SolidityFunctionWrapperGenerator.run(SolidityFunctionWrapperGenerator.java:41)
	at org.web3j.console.Runner.main(Runner.java:35)
`

#### contract source
`
pragma solidity >=0.4.22;

contract Eventer {

    event TestInt8(int8 indexed out1, int8 indexed out2);
    event AnonEvent(address, address);

    function getEvent() public {
        // set to 2,3 for functioning filter
        emit TestInt8(-2, -3);
    }
}
`

**Comment by danielgogo** [comment]
fix  https://github.com/PlatONnetwork/client-sdk-java/commit/001ef9c0d6a5bfc2d422f4abfdcddc46bc8b0897
