### ISSUE TITLE
Frequently call `debug_consensusStatus`  cause panic

### ISSUE THREAD

**Issue by mowind** [PlatONnetwork/PlatON-Go#1444]
Hi there,

Call RPC interface `debug_consensusStatus` once in every second cause panic.

#### System information

PlatON version: 0.13.0
OS & Version: Linux
Commit hash : develop

#### Expected behaviour

Return the consensus status.

#### Actual behaviour

panic

#### Backtrace

````
fatal error: concurrent map read and map write

goroutine 3982112 [running]:
runtime.throw(0x13182f0, 0x21)
	/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc01ab1c228 sp=0xc01ab1c1f8 pc=0x4767b2
runtime.mapaccess2(0x117db80, 0xc006268e40, 0xc0477170a4, 0xc0477170a4, 0xc061f998f8)
	/usr/local/go/src/runtime/map.go:469 +0x258 fp=0xc01ab1c268 sp=0xc01ab1c228 pc=0x450018
reflect.mapaccess(0x117db80, 0xc006268e40, 0xc0477170a4, 0x1307f9d)
	/usr/local/go/src/runtime/map.go:1309 +0x3f fp=0xc01ab1c2a0 sp=0xc01ab1c268 pc=0x45222f
reflect.Value.MapIndex(0x117db80, 0xc03cff9d88, 0x195, 0x111b960, 0xc0477170a4, 0x8a, 0x1263ca0, 0xc00a09e140, 0x16)
	/usr/local/go/src/reflect/value.go:1166 +0x16d fp=0xc01ab1c318 sp=0xc01ab1c2a0 pc=0x4dccbd
encoding/json.mapEncoder.encode(0xc0058e8060, 0xc04e839f00, 0x117db80, 0xc03cff9d88, 0x195, 0x100)
	/usr/local/go/src/encoding/json/encode.go:800 +0x305 fp=0xc01ab1c490 sp=0xc01ab1c318 pc=0x588ed5
encoding/json.mapEncoder.encode-fm(0xc04e839f00, 0x117db80, 0xc03cff9d88, 0x195, 0x100)
	/usr/local/go/src/encoding/json/encode.go:776 +0x64 fp=0xc01ab1c4d0 sp=0xc01ab1c490 pc=0x594d24
encoding/json.structEncoder.encode(0xc0058ea360, 0x1, 0x1, 0xc0058b3f50, 0xc04e839f00, 0x11ae640, 0xc03cff9d88, 0x199, 0x1310100)
	/usr/local/go/src/encoding/json/encode.go:758 +0x2bb fp=0xc01ab1c570 sp=0xc01ab1c4d0 pc=0x58895b
encoding/json.structEncoder.encode-fm(0xc04e839f00, 0x11ae640, 0xc03cff9d88, 0x199, 0xc03cff0100)
	/usr/local/go/src/encoding/json/encode.go:729 +0x7f fp=0xc01ab1c5c8 sp=0xc01ab1c570 pc=0x594c9f
encoding/json.ptrEncoder.encode(0xc0058b3f80, 0xc04e839f00, 0x11a3fe0, 0xc03cff9d88, 0x16, 0x100)
	/usr/local/go/src/encoding/json/encode.go:914 +0x116 fp=0xc01ab1c688 sp=0xc01ab1c5c8 pc=0x589eb6
encoding/json.ptrEncoder.encode-fm(0xc04e839f00, 0x11a3fe0, 0xc03cff9d88, 0x16, 0xc05c400100)
	/usr/local/go/src/encoding/json/encode.go:899 +0x64 fp=0xc01ab1c6c8 sp=0xc01ab1c688 pc=0x594ea4
encoding/json.mapEncoder.encode(0xc0058e8270, 0xc04e839f00, 0x117dc40, 0xc001a020e0, 0x195, 0x100)
	/usr/local/go/src/encoding/json/encode.go:800 +0x354 fp=0xc01ab1c840 sp=0xc01ab1c6c8 pc=0x588f24
encoding/json.mapEncoder.encode-fm(0xc04e839f00, 0x117dc40, 0xc001a020e0, 0x195, 0x100)
	/usr/local/go/src/encoding/json/encode.go:776 +0x64 fp=0xc01ab1c880 sp=0xc01ab1c840 pc=0x594d24
encoding/json.structEncoder.encode(0xc0058ea2d0, 0x1, 0x1, 0xc0058b3fb0, 0xc04e839f00, 0x11ae7c0, 0xc001a020e0, 0x199, 0xc0435c0100)
	/usr/local/go/src/encoding/json/encode.go:758 +0x2bb fp=0xc01ab1c920 sp=0xc01ab1c880 pc=0x58895b
encoding/json.structEncoder.encode-fm(0xc04e839f00, 0x11ae7c0, 0xc001a020e0, 0x199, 0xc001a00100)
	/usr/local/go/src/encoding/json/encode.go:729 +0x7f fp=0xc01ab1c978 sp=0xc01ab1c920 pc=0x594c9f
encoding/json.ptrEncoder.encode(0xc0058f4000, 0xc04e839f00, 0x11c84e0, 0xc020a44408, 0x196, 0x100)
	/usr/local/go/src/encoding/json/encode.go:914 +0x116 fp=0xc01ab1ca38 sp=0xc01ab1c978 pc=0x589eb6
encoding/json.ptrEncoder.encode-fm(0xc04e839f00, 0x11c84e0, 0xc020a44408, 0x196, 0x100)
	/usr/local/go/src/encoding/json/encode.go:899 +0x64 fp=0xc01ab1ca78 sp=0xc01ab1ca38 pc=0x594ea4
encoding/json.structEncoder.encode(0xc000158400, 0xa, 0x10, 0xc0058f4030, 0xc04e839f00, 0x1294240, 0xc020a443c0, 0x199, 0x1170100)
	/usr/local/go/src/encoding/json/encode.go:758 +0x2bb fp=0xc01ab1cb18 sp=0xc01ab1ca78 pc=0x58895b
encoding/json.structEncoder.encode-fm(0xc04e839f00, 0x1294240, 0xc020a443c0, 0x199, 0xc020a40100)
	/usr/local/go/src/encoding/json/encode.go:729 +0x7f fp=0xc01ab1cb70 sp=0xc01ab1cb18 pc=0x594c9f
encoding/json.ptrEncoder.encode(0xc0058f4060, 0xc04e839f00, 0x10de980, 0xc020a443c0, 0x16, 0x10d0100)
	/usr/local/go/src/encoding/json/encode.go:914 +0x116 fp=0xc01ab1cc30 sp=0xc01ab1cb70 pc=0x589eb6
encoding/json.ptrEncoder.encode-fm(0xc04e839f00, 0x10de980, 0xc020a443c0, 0x16, 0xc001e80100)
	/usr/local/go/src/encoding/json/encode.go:899 +0x64 fp=0xc01ab1cc70 sp=0xc01ab1cc30 pc=0x594ea4
encoding/json.(*encodeState).reflectValue(0xc04e839f00, 0x10de980, 0xc020a443c0, 0x16, 0xc01ab10100)
	/usr/local/go/src/encoding/json/encode.go:358 +0x82 fp=0xc01ab1cca8 sp=0xc01ab1cc70 pc=0x585e92
encoding/json.(*encodeState).marshal(0xc04e839f00, 0x10de980, 0xc020a443c0, 0x100, 0x0, 0x0)
	/usr/local/go/src/encoding/json/encode.go:330 +0xf0 fp=0xc01ab1cd08 sp=0xc01ab1cca8 pc=0x5859b0
encoding/json.Marshal(0x10de980, 0xc020a443c0, 0xc012535300, 0xc01ab1cdc8, 0x44c443, 0x1194180, 0x11c8440)
	/usr/local/go/src/encoding/json/encode.go:161 +0x52 fp=0xc01ab1cd80 sp=0xc01ab1cd08 pc=0x584e92
github.com/PlatONnetwork/PlatONE-Go/consensus/cbft/state.(*view).MarshalJSON(0xc0001cc230, 0x11c8440, 0xc0001cc230, 0x7f1cb40434d0, 0xc0001cc230, 0xc0001cc201)
	/PlatONE-Go/build/_workspace/src/github.com/PlatONnetwork/PlatONE-Go/consensus/cbft/state/state.go:362 +0x10f fp=0xc01ab1cdd8 sp=0xc01ab1cd80 pc=0xcfa4ef
encoding/json.marshalerEncoder(0xc05b047800, 0x11c8440, 0xc012535300, 0x196, 0x100)
	/usr/local/go/src/encoding/json/encode.go:477 +0xba fp=0xc01ab1ce58 sp=0xc01ab1cdd8 pc=0x58681a
encoding/json.structEncoder.encode(0xc0058c0b40, 0x4, 0x4, 0xc0058b3890, 0xc05b047800, 0x1230180, 0xc012535300, 0x199, 0x1170100)
	/usr/local/go/src/encoding/json/encode.go:758 +0x2bb fp=0xc01ab1cef8 sp=0xc01ab1ce58 pc=0x58895b
encoding/json.structEncoder.encode-fm(0xc05b047800, 0x1230180, 0xc012535300, 0x199, 0xc012530100)
	/usr/local/go/src/encoding/json/encode.go:729 +0x7f fp=0xc01ab1cf50 sp=0xc01ab1cef8 pc=0x594c9f
encoding/json.ptrEncoder.encode(0xc0058b38c0, 0xc05b047800, 0x10de8c0, 0xc012535300, 0x16, 0x10d0100)
	/usr/local/go/src/encoding/json/encode.go:914 +0x116 fp=0xc01ab1d010 sp=0xc01ab1cf50 pc=0x589eb6
encoding/json.ptrEncoder.encode-fm(0xc05b047800, 0x10de8c0, 0xc012535300, 0x16, 0x1f50100)
	/usr/local/go/src/encoding/json/encode.go:899 +0x64 fp=0xc01ab1d050 sp=0xc01ab1d010 pc=0x594ea4
encoding/json.(*encodeState).reflectValue(0xc05b047800, 0x10de8c0, 0xc012535300, 0x16, 0xc01ab10100)
	/usr/local/go/src/encoding/json/encode.go:358 +0x82 fp=0xc01ab1d088 sp=0xc01ab1d050 pc=0x585e92
encoding/json.(*encodeState).marshal(0xc05b047800, 0x10de8c0, 0xc012535300, 0xc01ab10100, 0x0, 0x0)
	/usr/local/go/src/encoding/json/encode.go:330 +0xf0 fp=0xc01ab1d0e8 sp=0xc01ab1d088 pc=0x5859b0
encoding/json.Marshal(0x10de8c0, 0xc012535300, 0xc7202850fea5e19f, 0x7909f97ca7a19259, 0x4fe2526af938a2, 0x1, 0x1e0e360)
	/usr/local/go/src/encoding/json/encode.go:161 +0x52 fp=0xc01ab1d160 sp=0xc01ab1d0e8 pc=0x584e92
github.com/PlatONnetwork/PlatONE-Go/consensus/cbft/state.(*ViewState).MarshalJSON(0xc0001cc2d0, 0x12d9680, 0xc0001cc2d0, 0x7f1cb40434b0, 0xc0001cc2d0, 0xc0001cc201)
	/PlatONE-Go/build/_workspace/src/github.com/PlatONnetwork/PlatONE-Go/consensus/cbft/state/state.go:725 +0x38b fp=0xc01ab1d280 sp=0xc01ab1d160 pc=0xcfcdeb
encoding/json.marshalerEncoder(0xc03d314e00, 0x12d9680, 0xc01c453388, 0x196, 0x100)
	/usr/local/go/src/encoding/json/encode.go:477 +0xba fp=0xc01ab1d300 sp=0xc01ab1d280 pc=0x58681a
encoding/json.structEncoder.encode(0xc0058c0480, 0x3, 0x4, 0xc0058b3320, 0xc03d314e00, 0x1201d80, 0xc01c453380, 0x199, 0x1170100)
	/usr/local/go/src/encoding/json/encode.go:758 +0x2bb fp=0xc01ab1d3a0 sp=0xc01ab1d300 pc=0x58895b
encoding/json.structEncoder.encode-fm(0xc03d314e00, 0x1201d80, 0xc01c453380, 0x199, 0xc01c450100)
	/usr/local/go/src/encoding/json/encode.go:729 +0x7f fp=0xc01ab1d3f8 sp=0xc01ab1d3a0 pc=0x594c9f
encoding/json.ptrEncoder.encode(0xc0058b3380, 0xc03d314e00, 0x10de240, 0xc01c453380, 0x16, 0x10d0100)
	/usr/local/go/src/encoding/json/encode.go:914 +0x116 fp=0xc01ab1d4b8 sp=0xc01ab1d3f8 pc=0x589eb6
encoding/json.ptrEncoder.encode-fm(0xc03d314e00, 0x10de240, 0xc01c453380, 0x16, 0xc01c450100)
	/usr/local/go/src/encoding/json/encode.go:899 +0x64 fp=0xc01ab1d4f8 sp=0xc01ab1d4b8 pc=0x594ea4
encoding/json.(*encodeState).reflectValue(0xc03d314e00, 0x10de240, 0xc01c453380, 0x16, 0xc01c450100)
	/usr/local/go/src/encoding/json/encode.go:358 +0x82 fp=0xc01ab1d530 sp=0xc01ab1d4f8 pc=0x585e92
encoding/json.interfaceEncoder(0xc03d314e00, 0x115ec80, 0xc009b4e950, 0x194, 0x100)
	/usr/local/go/src/encoding/json/encode.go:713 +0xac fp=0xc01ab1d578 sp=0xc01ab1d530 pc=0x5884bc
encoding/json.structEncoder.encode(0xc003a3eb40, 0x3, 0x4, 0xc003a15a70, 0xc03d314e00, 0x1206940, 0xc009b4e930, 0x199, 0x1170100)
	/usr/local/go/src/encoding/json/encode.go:758 +0x2bb fp=0xc01ab1d618 sp=0xc01ab1d578 pc=0x58895b
encoding/json.structEncoder.encode-fm(0xc03d314e00, 0x1206940, 0xc009b4e930, 0x199, 0xc009b40100)
	/usr/local/go/src/encoding/json/encode.go:729 +0x7f fp=0xc01ab1d670 sp=0xc01ab1d618 pc=0x594c9f
encoding/json.ptrEncoder.encode(0xc003a15aa0, 0xc03d314e00, 0x10e5480, 0xc009b4e930, 0x16, 0x10e0100)
	/usr/local/go/src/encoding/json/encode.go:914 +0x116 fp=0xc01ab1d730 sp=0xc01ab1d670 pc=0x589eb6
encoding/json.ptrEncoder.encode-fm(0xc03d314e00, 0x10e5480, 0xc009b4e930, 0x16, 0x1f50100)
	/usr/local/go/src/encoding/json/encode.go:899 +0x64 fp=0xc01ab1d770 sp=0xc01ab1d730 pc=0x594ea4
encoding/json.(*encodeState).reflectValue(0xc03d314e00, 0x10e5480, 0xc009b4e930, 0x16, 0xc076810100)
	/usr/local/go/src/encoding/json/encode.go:358 +0x82 fp=0xc01ab1d7a8 sp=0xc01ab1d770 pc=0x585e92
encoding/json.(*encodeState).marshal(0xc03d314e00, 0x10e5480, 0xc009b4e930, 0x7a02da8cd8ea0100, 0x0, 0x0)
	/usr/local/go/src/encoding/json/encode.go:330 +0xf0 fp=0xc01ab1d808 sp=0xc01ab1d7a8 pc=0x5859b0
encoding/json.(*Encoder).Encode(0xc020a44190, 0x10e5480, 0xc009b4e930, 0xc001fefb50, 0x16)
	/usr/local/go/src/encoding/json/stream.go:206 +0x8a fp=0xc01ab1d898 sp=0xc01ab1d808 pc=0x5929ea
encoding/json.(*Encoder).Encode-fm(0x10e5480, 0xc009b4e930, 0xc0587797a6, 0xf)
	/usr/local/go/src/encoding/json/stream.go:201 +0x3e fp=0xc01ab1d8d0 sp=0xc01ab1d898 pc=0x99492e
github.com/PlatONnetwork/PlatONE-Go/rpc.(*jsonCodec).Write(0xc020a441e0, 0x10e5480, 0xc009b4e930, 0x0, 0x0)
	/PlatONE-Go/build/_workspace/src/github.com/PlatONnetwork/PlatONE-Go/rpc/json.go:350 +0x84 fp=0xc01ab1d920 sp=0xc01ab1d8d0 pc=0x98b0b4
github.com/PlatONnetwork/PlatONE-Go/rpc.(*Server).exec(0xc0025f4270, 0x158ae20, 0xc0305ead00, 0x1596860, 0xc020a441e0, 0xc056f4e5a0)
	/PlatONE-Go/build/_workspace/src/github.com/PlatONnetwork/PlatONE-Go/rpc/server.go:333 +0xa4 fp=0xc01ab1d990 sp=0xc01ab1d920 pc=0x98e174
github.com/PlatONnetwork/PlatONE-Go/rpc.(*Server).serveRequest(0xc0025f4270, 0x158aee0, 0xc009b4e2a0, 0x1596860, 0xc020a441e0, 0xc03db4ff01, 0x1, 0x0, 0x0)
	/PlatONE-Go/build/_workspace/src/github.com/PlatONnetwork/PlatONE-Go/rpc/server.go:192 +0x426 fp=0xc01ab1daa0 sp=0xc01ab1d990 pc=0x98c216
github.com/PlatONnetwork/PlatONE-Go/rpc.(*Server).ServeSingleRequest(...)
	/PlatONE-Go/build/_workspace/src/github.com/PlatONnetwork/PlatONE-Go/rpc/server.go:223
github.com/PlatONnetwork/PlatONE-Go/rpc.(*Server).ServeHTTP(0xc0025f4270, 0x1584fa0, 0xc0601e7880, 0xc00038c700)
	/PlatONE-Go/build/_workspace/src/github.com/PlatONnetwork/PlatONE-Go/rpc/http.go:247 +0x4e0 fp=0xc01ab1db88 sp=0xc01ab1daa0 pc=0x986c80
github.com/PlatONnetwork/PlatONE-Go/rpc.(*virtualHostHandler).ServeHTTP(0xc0025e7c60, 0x1584fa0, 0xc0601e7880, 0xc00038c700)
	/PlatONE-Go/build/_workspace/src/github.com/PlatONnetwork/PlatONE-Go/rpc/http.go:305 +0x200 fp=0xc01ab1dbe8 sp=0xc01ab1db88 pc=0x9874a0
net/http.serverHandler.ServeHTTP(0xc0001ba8c0, 0x1584fa0, 0xc0601e7880, 0xc00038c700)
	/usr/local/go/src/net/http/server.go:2807 +0xa3 fp=0xc01ab1dc18 sp=0xc01ab1dbe8 pc=0x89ae13
net/http.(*conn).serve(0xc00c489f40, 0x158ae20, 0xc01d542000)
	/usr/local/go/src/net/http/server.go:1895 +0x86c fp=0xc01ab1dfc8 sp=0xc01ab1dc18 pc=0x89678c
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc01ab1dfd0 sp=0xc01ab1dfc8 pc=0x4a98e1
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2933 +0x35c
````

**Comment by mowind** [comment]
Fix in #1448
