### ISSUE TITLE
Restart the node, "panic" occurs

### ISSUE THREAD

**Issue by lipingD** [PlatONnetwork/PlatON-Go#535]

**Comment by lipingD** [comment]
panic: get unknown epoch, current:2, request:3panic: get unknown epoch, current:2, request:3
goroutine 100 [running]:github.com/PlatONnetwork/PlatON-Go/consensus/cbft/validator.(*ValidatorPool).epochToBlockNumber(0xc0000a25a0, 0x3, 0xc0000a25b0) /home/platon/Jenkins/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/consensus/cbft/validator/validator.go:566 +0x154github.com/PlatONnetwork/PlatON-Go/consensus/cbft/validator.(*ValidatorPool).Len(0xc0000a25a0, 0x3, 0x0) /home/platon/Jenkins/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/consensus/cbft/validator/validator.go:490 +0x81github.com/PlatONnetwork/PlatON-Go/consensus/cbft.(*Cbft).currentValidatorLen(0xc0002d0000, 0x0) /home/platon/Jenkins/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/consensus/cbft/cbft.go:1269 +0x44github.com/PlatONnetwork/PlatON-Go/consensus/cbft.(*Cbft).MissingPrepareVote.func1() /home/platon/Jenkins/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/consensus/cbft/sync_process.go:467 +0xbcgithub.com/PlatONnetwork/PlatON-Go/consensus/cbft.(*Cbft).receiveLoop(0xc0002d0000) /home/platon/Jenkins/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/consensus/cbft/cbft.go:490 +0x2b9created by github.com/PlatONnetwork/PlatON-Go/consensus/cbft.(*Cbft).Start /home/platon/Jenkins/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/consensus/cbft/cbft.go:264 +0x6e1

**Comment by lipingD** [comment]
Verification is complete, no problem
