### ISSUE TITLE
panic when run 'platon copydb  xx xx'

### ISSUE THREAD

**Issue by jiangshangqifeng** [PlatONnetwork/PlatON-Go#542]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

#### System information

PlatON version: `platon version`
OS & Version: Windows/Linux/OSX
Commit hash : 704cbc32089059bf67b2be5913e42020b7ab7b98

#### Expected behaviour
copy success

#### Actual behaviour
panic occured

#### Backtrace

````
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0xa2152a]

goroutine 1 [running]:
github.com/PlatONnetwork/PlatON-Go/core/snapshotdb.(*snapshotDB).recover(0xc001f9f668, 0x184a500, 0xc0001250a0, 0x0, 0x0)
        D:/go/src/github.com/PlatONnetwork/PlatON-Go/core/snapshotdb/db.go:109 +0x1ba
github.com/PlatONnetwork/PlatON-Go/core/snapshotdb.initDB(0xc0001e72a0, 0x15cac49)
        D:/go/src/github.com/PlatONnetwork/PlatON-Go/core/snapshotdb/snapshotdb.go:246 +0x43c
github.com/PlatONnetwork/PlatON-Go/core/snapshotdb.Instance(0x0, 0x0)
        D:/go/src/github.com/PlatONnetwork/PlatON-Go/core/snapshotdb/snapshotdb.go:177 +0x169
main.copyDb(0xc0001082c0, 0x15c1174, 0x9)
        D:/go/src/github.com/PlatONnetwork/PlatON-Go/cmd/platon/chaincmd.go:439 +0x104
github.com/PlatONnetwork/PlatON-Go/cmd/utils.MigrateFlags.func1(0xc0001082c0, 0x0, 0xc0001082c0)
        D:/go/src/github.com/PlatONnetwork/PlatON-Go/cmd/utils/flags.go:1571 +0xc5
github.com/PlatONnetwork/PlatON-Go/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0x140f380, 0xc0001ac410, 0xc0001082c0, 0xc000373000, 0x0)
        D:/go/src/github.com/PlatONnetwork/PlatON-Go/vendor/gopkg.in/urfave/cli.v1/app.go:490 +0xcf
github.com/PlatONnetwork/PlatON-Go/vendor/gopkg.in/urfave/cli%2ev1.Command.Run(0x15bca87, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x15f60e3, 0x33, 0x0, ...)
        D:/go/src/github.com/PlatONnetwork/PlatON-Go/vendor/gopkg.in/urfave/cli.v1/command.go:210 +0x99d
github.com/PlatONnetwork/PlatON-Go/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc0000b2d00, 0xc0000720c0, 0x4, 0x4, 0x0, 0x0)
        D:/go/src/github.com/PlatONnetwork/PlatON-Go/vendor/gopkg.in/urfave/cli.v1/app.go:255 +0x6b6
main.main()
        D:/go/src/github.com/PlatONnetwork/PlatON-Go/cmd/platon/main.go:281 +0x5c
````

**Comment by benbaley** [comment]
close by done
