### ISSUE TITLE
Maybe panic appears when my consensus node initiates fast mode synchronization

### ISSUE THREAD

**Issue by awake006** [PlatONnetwork/PlatON-Go#745]
Hi there,

Maybe panic appears when my consensus node initiates fast mode synchronization

#### System information

PlatON version: 0.7.4
OS & Version: Linux
Commit hash : 16207eb24892c9adae20bf68bf1cd7feaa6bf996

#### Steps to reproduce the behaviour
I started four consensus nodes. After running for about 100 seconds, close one, delete the database, and start using fast mode.

#### Backtrace

````
TRACE[11-14|06:05:59.187|miner/worker.go:1280]                      Check should commit                      shouldCommit=true  status=0 timestamp=2019-11-14T06:05:59+0000  nextBlockTime=2019-11-14T06:05:59+0000
DEBUG[11-14|06:05:59.187|miner/worker.go:1297]                      Check if time's up in shouldCommit()     result=true current.number=0 current.hash=430583…44a771 current.timestamp="1970-01-18 19:45:18.474" next.number=0 next.hash=430583…44a771 next.timestamp="1970-01-18 19:45:18.474" nextBlockTime=2019-11-14T06:05:59+0000 timestamp=2019-11-14T06:05:59+0000
DEBUG[11-14|06:05:59.187|miner/worker.go:424]                       Begin to package new block regularly 
DEBUG[11-14|06:05:59.187|consensus/cbft/cbft.go:302]                Invalid msg                              epoch=1 view=0                      peer=a578938c64855457 type=*protocols.PrepareBlock     msg={Epoch:5,ViewNumber:1,Hash:37dfcc…654973,Number:169,BlockIndex:3,ProposalIndex:1,ParentHash:1ecf8f…b531c5}
DEBUG[11-14|06:05:59.188|consensus/cbft/cbft.go:1132]               Calc block deadline                      epoch=1 view=0                      timePoint=2019-11-14T06:05:59+0000 stateDeadline=2019-11-14T06:06:02+0000 produceInterval=1s rtt=200ms         executeTime=400ms
INFO [11-14|06:05:59.188|miner/worker.go:339]                       Begin to commit new worker               baseBlockHash=430583…44a771 baseBlockNumber=0 timestamp=1573711559187             deadline=1573711559587            deadlineDuration=400ms
DEBUG[11-14|06:05:59.188|core/snapshotdb/snapshotdb.go:167]         dbInstance is nil                        package=snapshotdb        path=/home/platon/trantor_test/node-16789/data/platon/snapshotdb
ERROR[11-14|06:05:59.188|core/snapshotdb/snapshotdb.go:182]         open db file fail                        package=snapshotdb        error="newFileLock fail:resource temporarily unavailable" path=/home/platon/trantor_test/node-16789/data/platon/snapshotdb
ERROR[11-14|06:05:59.188|core/snapshotdb/snapshotdb.go:172]         init db fail                             package=snapshotdb        err="newFileLock fail:resource temporarily unavailable"
DEBUG[11-14|06:05:59.188|consensus/cbft/cbft.go:1144]               Calc next block time                     epoch=1 view=0                      blockTime=2019-11-14T06:05:59+0000 now=2019-11-14T06:05:59+0000 produceInterval=1s period=10000 amount=10 interval=1.347646ms              rtt=200ms         executeTime=400ms
DEBUG[11-14|06:05:59.188|miner/worker.go:1014]                      Next block time                          time="2019-11-14 06:05:59.787"
panic: newFileLock fail:resource temporarily unavailable

goroutine 98 [running]:
github.com/PlatONnetwork/PlatON-Go/core/snapshotdb.Instance(0x0, 0x0)
	/home/platon/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/core/snapshotdb/snapshotdb.go:173 +0x33f
github.com/PlatONnetwork/PlatON-Go/x/gov.get(0x0, 0x0, 0x0, 0x0, 0xc000238510, 0x21, 0x21, 0x21, 0x21, 0x4, ...)
	/home/platon/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/x/gov/gov_snapdb.go:31 +0x26
github.com/PlatONnetwork/PlatON-Go/x/gov.findGovernParamValue(0x12f2d38, 0x5, 0x1301051, 0x10, 0x0, 0x0, 0x0, 0x0, 0x8, 0x489d81, ...)
	/home/platon/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/x/gov/gov_snapdb.go:229 +0x1a0
github.com/PlatONnetwork/PlatON-Go/x/gov.GetGovernParamValue(0x12f2d38, 0x5, 0x1301051, 0x10, 0x1, 0x0, 0x0, 0x0, 0x0, 0x8, ...)
	/home/platon/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/x/gov/gov.go:591 +0x6a
github.com/PlatONnetwork/PlatON-Go/x/gov.GovernMaxBlockGasLimit(0x1, 0x0, 0x0, 0x0, 0x0, 0xc0090e31f8, 0x5592ee, 0xc00934fb50)
	/home/platon/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/x/gov/gov.go:729 +0x84
github.com/PlatONnetwork/PlatON-Go/core.CalcGasLimit(0xc00029aa80, 0x47e7c4, 0xc00000e6c0)
	/home/platon/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/core/block_validator.go:112 +0x106
github.com/PlatONnetwork/PlatON-Go/miner.(*worker).commitNewWork(0xc00000c1e0, 0xc00934fab0, 0x0, 0x16e6884ba13, 0xc00029aa80, 0xbf6b5991e30958d4, 0x1aa605b92, 0x2357f00)
	/home/platon/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/miner/worker.go:1041 +0x2bd
github.com/PlatONnetwork/PlatON-Go/miner.(*worker).mainLoop(0xc00000c1e0)
	/home/platon/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/miner/worker.go:495 +0x911
created by github.com/PlatONnetwork/PlatON-Go/miner.newWorker
	/home/platon/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/miner/worker.go:235 +0x7b5
````

**Comment by cheng762** [comment]
this semms you open a node with same direcotry twice,please close one before you open it

**Comment by awake006** [comment]
Oh, thanks.
