### ISSUE TITLE
0.7.3, admin.getSchnorrNIZKProve() cause panic for platon.

### ISSUE THREAD

**Issue by ckmonkey** [PlatONnetwork/PlatON-Go#871]
Hi,
 When I was getting proof, I had a trouble By using the 0.7.3 version.

#### cmd
```
 admin.getSchnorrNIZKProve()
```
#### Backtrace

````
fatal: morestack on g0
SIGTRAP: trace trap
PC=0x49eec2 m=21 sigcode=128

goroutine 0 [idle]:
runtime.abort()
        /usr/local/go/src/runtime/asm_amd64.s:839 +0x2
runtime.morestack()
        /usr/local/go/src/runtime/asm_amd64.s:397 +0x25

goroutine 661123 [syscall]:
runtime.cgocall(0xf57e10, 0xc003ed14b0, 0x11ce501)
        /usr/local/go/src/runtime/cgocall.go:128 +0x5b fp=0xc003ed1480 sp=0xc003ed1448 pc=0x44516b
github.com/PlatONnetwork/PlatON-Go/crypto/bls._Cfunc_blsGetPublicKey(0xc013beea20, 0xc003fba870)
        _cgo_gotypes.go:189 +0x41 fp=0xc003ed14b0 sp=0xc003ed1480 pc=0x764831
github.com/PlatONnetwork/PlatON-Go/crypto/bls.(*SecretKey).GetPublicKey(...)
        /PlatON-Go/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/crypto/bls/bls.go:382
github.com/PlatONnetwork/PlatON-Go/crypto/bls.(*SecretKey).MakeSchnorrNIZKP(0xc003fba870, 0x18, 0xc01d1f5920, 0xc01d53fea0)
        /PlatON-Go/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/crypto/bls/schnorrNIZK.go:92 +0x68 fp=0xc003ed15d0 sp=0xc003ed14b0 pc=0x763ce8
github.com/PlatONnetwork/PlatON-Go/consensus/cbft.(*Cbft).GetSchnorrNIZKProve(0xc000274200, 0x0, 0xc027771b90, 0x8)
````

**Comment by niuxiaojie81** [comment]
Whether to generate the blskey manually and specify the blskey in the startup command '--cbft.blskey'

**Comment by ckmonkey** [comment]
Yes, That's what i did.

**Comment by ckmonkey** [comment]
In my command for startup include: ` --nodekey ./data/nodekey --cbft.blskey ./data/blskey`

**Comment by niuxiaojie81** [comment]
This seems like an occasional problem and should be related to the runtime environment

**Comment by niuxiaojie81** [comment]
Please describe the system information and steps in detail, such as os system version, memory size, and compilation steps.
If BLS library-related functionality is not involved, does platon work properly
